const julia_packages = [
                   "IJulia", # DO NOT REMOVE
                   # add class specific classes here:
                   "CSV",
                   "DataFrames",
                   #"DataFramesMeta",
                   "Distributions",
                   #"ClassImbalance",
                   "Clustering",
                   "DecisionTree",
                   "Flux",
                   "GLM",
                   "HypothesisTests",
                   "Ipopt",
                   #"JuMP",
                   "Primes",
                   "Roots",
                   "Optim",
                   "StatsBase",
                   "MLDatasets",
                   "MLJ",
                   "Images",
                   "ProgressMeter",
                   "TableView",
                   "Query",
                   "QuadGK",
                   "NLopt",
                   "LaTeXStrings",
                   "Feather",
                   "Gadfly",
                   #"GR",
                   "Plots",
                   "VegaLite",
                   "RDatasets",
                   "MLDatasets",
                   "StatsPlots",
                   "Tidier"
                    ]
