name: build-image-basepackages
on: 
  push:
      paths:
      - 'requirements/classes/basepackages/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/basepackages.yml'

env:
  CLASS: basepackages
  TARGET: r_julia
  SQLITE: false
  PYTHON_VERSION: "3.9.17"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Create Julia Environment Files
        if: env.TARGET == 'r_julia'
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build

      - name: Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest us-east1-docker.pkg.dev/jupyterhub-docker-images/jupyterhub-docker-images/basepackages:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest us-east1-docker.pkg.dev/jupyterhub-docker-images/jupyterhub-docker-images/basepackages:latest
          docker push us-east1-docker.pkg.dev/jupyterhub-docker-images/jupyterhub-docker-images/basepackages:latest
          docker push us-east1-docker.pkg.dev/jupyterhub-docker-images/jupyterhub-docker-images/basepackages:${GITHUB_REF##*/}
