name: build-image-mpa2065
on: 
  push:
      paths:
      - 'requirements/classes/mpa2065/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/mpa2065.yml'

env:
  CLASS: mpa2065
  TARGET: r_julia
  SQLITE: true
  PYTHON_VERSION: "3.9.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Create Julia Environment Files
        if: env.TARGET == 'r_julia'
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build

      - name: Configure Docker
        run: gcloud auth configure-docker
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/mpa2065:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/mpa2065:latest
          docker push gcr.io/jupyterhub-docker-images/mpa2065:latest
          docker push gcr.io/jupyterhub-docker-images/mpa2065:${GITHUB_REF##*/}
