name: tag-image-mpa2065
on: [workflow_dispatch]

env:
  CLASS: mpa2065
  TARGET: r_julia
  SQLITE: false
  PYTHON_VERSION: "3.9.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@v0.6.2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Create Julia Environment Files
        if: env.TARGET == 'r_julia'
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build

      - name: Upload Julia Env Files to Google Storage Bucket
        if: env.TARGET == 'r_julia'
        run: |
          gsutil cp -r requirements/classes/mpa2065/julia_env gs://jupyterhub-environment-files/fall-2024/mpa2065/past/${GITHUB_SHA}/julia
          gsutil cp -r requirements/classes/mpa2065/julia_env gs://jupyterhub-environment-files/fall-2024/mpa2065/latest/julia

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest pkg.dev/jupyterhub-docker-images/mpa2065:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest pkg.dev/jupyterhub-docker-images/mpa2065:${GITHUB_SHA}
          docker tag jupyterhub-docker-images_jh_image:latest pkg.dev/jupyterhub-docker-images/mpa2065:latest
          docker tag jupyterhub-docker-images_jh_image:latest pkg.dev/jupyterhub-docker-images/mpa2065:fall-2024
          docker push pkg.dev/jupyterhub-docker-images/mpa2065:latest
          docker push pkg.dev/jupyterhub-docker-images/mpa2065:fall-2024
          docker push pkg.dev/jupyterhub-docker-images/mpa2065:${GITHUB_REF##*/}
          docker push pkg.dev/jupyterhub-docker-images/mpa2065:${GITHUB_SHA}

      - name: Upload Conda Env Files to Google Storage Bucket
        run: |
          gsutil cp -r requirements/out gs://jupyterhub-environment-files/fall-2024/mpa2065/past/${GITHUB_SHA}/conda
          gsutil cp -r requirements/out gs://jupyterhub-environment-files/fall-2024/mpa2065/latest/conda